// [追加] 東京競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/tokyo/tokyo_base.dart';

class TokyoCourse {
  static const RaceCourseData shiba1400 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:59:52
    // Result: tokyo shiba 1400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 340.4),
      CourseSection(name: 'straight', startDistance: 340.4, endDistance: 655.2),
      CourseSection(name: 'corner_4', startDistance: 655.2, endDistance: 874.1),
      CourseSection(name: 'finish', startDistance: 874.1, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData shiba1600 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 1600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 02:00:17
    // Result: tokyo shiba 1600m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 0.0, distance: 84.8),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 84.8),
      CourseSection(name: 'backstretch', startDistance: 84.8, endDistance: 560.2),
      CourseSection(name: 'corner_3', startDistance: 560.2, endDistance: 864.6),
      CourseSection(name: 'corner_4', startDistance: 864.6, endDistance: 1074.1),
      CourseSection(name: 'finish', startDistance: 1074.1, endDistance: 1600.0),
    ],
  );

  static const RaceCourseData shiba1800 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 02:00:51
    // Result: tokyo shiba 1800m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 39.38, distance: 120.5),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 120.5),
      CourseSection(name: 'corner_2', startDistance: 120.5, endDistance: 284.8),
      CourseSection(name: 'backstretch', startDistance: 284.8, endDistance: 760.2),
      CourseSection(name: 'corner_3', startDistance: 760.2, endDistance: 1064.6),
      CourseSection(name: 'corner_4', startDistance: 1064.6, endDistance: 1274.1),
      CourseSection(name: 'finish', startDistance: 1274.1, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shiba2000 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 02:02:27
    // Result: tokyo shiba 2000m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 1.47, distance: 138.3),
      CourseApproach(angle: 19.98, distance: 41.5),
      CourseApproach(angle: 42.88, distance: 33.9),
      CourseApproach(angle: 54.87, distance: 58.5),
      CourseApproach(angle: 67.17, distance: 36.5),
      CourseApproach(angle: 79.7, distance: 39.6),
      CourseApproach(angle: 91.49, distance: 136.5),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 484.8),
      CourseSection(name: 'backstretch', startDistance: 484.8, endDistance: 960.2),
      CourseSection(name: 'corner_3', startDistance: 960.2, endDistance: 1264.6),
      CourseSection(name: 'corner_4', startDistance: 1264.6, endDistance: 1474.1),
      CourseSection(name: 'finish', startDistance: 1474.1, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shiba2300 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 2300,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 02:03:08
    // Result: tokyo shiba 2300m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 255.5),
      CourseSection(name: 'corner_1', startDistance: 255.5, endDistance: 482.8),
      CourseSection(name: 'corner_2', startDistance: 482.8, endDistance: 784.8),
      CourseSection(name: 'backstretch', startDistance: 784.8, endDistance: 1260.2),
      CourseSection(name: 'corner_3', startDistance: 1260.2, endDistance: 1564.6),
      CourseSection(name: 'corner_4', startDistance: 1564.6, endDistance: 1774.1),
      CourseSection(name: 'finish', startDistance: 1774.1, endDistance: 2300.0),
    ],
  );

  static const RaceCourseData shiba2400 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 02:59:57
    // Result: tokyo shiba 2400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 355.5),
      CourseSection(name: 'corner_1', startDistance: 355.5, endDistance: 582.8),
      CourseSection(name: 'corner_2', startDistance: 582.8, endDistance: 884.8),
      CourseSection(name: 'backstretch', startDistance: 884.8, endDistance: 1360.2),
      CourseSection(name: 'corner_3', startDistance: 1360.2, endDistance: 1664.6),
      CourseSection(name: 'corner_4', startDistance: 1664.6, endDistance: 1874.1),
      CourseSection(name: 'finish', startDistance: 1874.1, endDistance: 2400.0),
    ],
  );

  static const RaceCourseData shiba2500 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 2500,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:00:29
    // Result: tokyo shiba 2500m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 455.5),
      CourseSection(name: 'corner_1', startDistance: 455.5, endDistance: 682.8),
      CourseSection(name: 'corner_2', startDistance: 682.8, endDistance: 984.8),
      CourseSection(name: 'backstretch', startDistance: 984.8, endDistance: 1460.2),
      CourseSection(name: 'corner_3', startDistance: 1460.2, endDistance: 1764.6),
      CourseSection(name: 'corner_4', startDistance: 1764.6, endDistance: 1974.1),
      CourseSection(name: 'finish', startDistance: 1974.1, endDistance: 2500.0),
    ],
  );

  static const RaceCourseData shiba3400 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 3400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:01:30
    // Result: tokyo shiba 3400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 277.1),
      CourseSection(name: 'corner_3', startDistance: 277.1, endDistance: 581.5),
      CourseSection(name: 'corner_4', startDistance: 581.5, endDistance: 791.0),
      CourseSection(name: 'home_straight', startDistance: 791.0, endDistance: 1355.5),
      CourseSection(name: 'corner_1', startDistance: 1355.5, endDistance: 1582.8),
      CourseSection(name: 'corner_2', startDistance: 1582.8, endDistance: 1884.8),
      CourseSection(name: 'backstretch', startDistance: 1884.8, endDistance: 2360.2),
      CourseSection(name: 'corner_3', startDistance: 2360.2, endDistance: 2664.6),
      CourseSection(name: 'corner_4', startDistance: 2664.6, endDistance: 2874.1),
      CourseSection(name: 'finish', startDistance: 2874.1, endDistance: 3400.0),
    ],
  );

  static const RaceCourseData dirt1300 = RaceCourseData(
    baseData: TokyoBase.dirt,
    raceDistance: 1300,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:01:58
    // Result: tokyo dirt 1300m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 365.7),
      CourseSection(name: 'corner_3', startDistance: 365.7, endDistance: 613.4),
      CourseSection(name: 'corner_4', startDistance: 613.4, endDistance: 798.4),
      CourseSection(name: 'finish', startDistance: 798.4, endDistance: 1300.0),
    ],
  );

  static const RaceCourseData dirt1400 = RaceCourseData(
    baseData: TokyoBase.dirt,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:02:21
    // Result: tokyo dirt 1400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 465.7),
      CourseSection(name: 'corner_3', startDistance: 465.7, endDistance: 713.4),
      CourseSection(name: 'corner_4', startDistance: 713.4, endDistance: 898.4),
      CourseSection(name: 'finish', startDistance: 898.4, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData dirt1600 = RaceCourseData(
    baseData: TokyoBase.dirt,
    raceDistance: 1600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:02:48
    // Result: tokyo dirt 1600m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 0.0, distance: 194.8),
    ],

    sections: const [
      CourseSection(name: 'start_turf', startDistance: 0.0, endDistance: 102.9),
      CourseSection(name: 'start_dirt', startDistance: 102.9, endDistance: 194.8),
      CourseSection(name: 'backstretch', startDistance: 194.8, endDistance: 665.7),
      CourseSection(name: 'corner_3', startDistance: 665.7, endDistance: 913.4),
      CourseSection(name: 'corner_4', startDistance: 913.4, endDistance: 1098.4),
      CourseSection(name: 'finish', startDistance: 1098.4, endDistance: 1600.0),
    ],
  );

  static const RaceCourseData dirt2100 = RaceCourseData(
    baseData: TokyoBase.dirt,
    raceDistance: 2100,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:03:20
    // Result: tokyo dirt 2100m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 240.7),
      CourseSection(name: 'corner_1', startDistance: 240.7, endDistance: 425.9),
      CourseSection(name: 'corner_2', startDistance: 425.9, endDistance: 694.8),
      CourseSection(name: 'backstretch', startDistance: 694.8, endDistance: 1165.7),
      CourseSection(name: 'corner_3', startDistance: 1165.7, endDistance: 1413.4),
      CourseSection(name: 'corner_4', startDistance: 1413.4, endDistance: 1598.4),
      CourseSection(name: 'finish', startDistance: 1598.4, endDistance: 2100.0),
    ],
  );

  static const RaceCourseData dirt2400 = RaceCourseData(
    baseData: TokyoBase.dirt,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-13 23:21:07
    // Result: tokyo dirt 2400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 540.7),
      CourseSection(name: 'corner_1', startDistance: 540.7, endDistance: 725.9),
      CourseSection(name: 'corner_2', startDistance: 725.9, endDistance: 994.8),
      CourseSection(name: 'backstretch', startDistance: 994.8, endDistance: 1465.7),
      CourseSection(name: 'corner_3', startDistance: 1465.7, endDistance: 1713.4),
      CourseSection(name: 'corner_4', startDistance: 1713.4, endDistance: 1898.4),
      CourseSection(name: 'finish', startDistance: 1898.4, endDistance: 2400.0),
    ],
  );

  static const RaceCourseData dirt1200 = RaceCourseData(
    baseData: TokyoBase.dirt,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-13 23:21:31
    // Result: tokyo dirt 1200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 265.7),
      CourseSection(name: 'corner_3', startDistance: 265.7, endDistance: 513.4),
      CourseSection(name: 'corner_4', startDistance: 513.4, endDistance: 698.4),
      CourseSection(name: 'finish', startDistance: 698.4, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shiba2600 = RaceCourseData(
    baseData: TokyoBase.shiba,
    raceDistance: 2600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-13 23:22:08
    // Result: tokyo shiba 2600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 555.5),
      CourseSection(name: 'corner_1', startDistance: 555.5, endDistance: 782.8),
      CourseSection(name: 'corner_2', startDistance: 782.8, endDistance: 1084.8),
      CourseSection(name: 'backstretch', startDistance: 1084.8, endDistance: 1560.2),
      CourseSection(name: 'corner_3', startDistance: 1560.2, endDistance: 1864.6),
      CourseSection(name: 'corner_4', startDistance: 1864.6, endDistance: 2074.1),
      CourseSection(name: 'finish', startDistance: 2074.1, endDistance: 2600.0),
    ],
  );

}
