// [自動生成] 新潟競馬場 レース距離別データ
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/niigata/niigata_base.dart';

class NiigataCourse {
  static const RaceCourseData shibaInner1200 = RaceCourseData(
    baseData: NiigataBase.shibaInner,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:38:21
    // Result: niigata shiba_inner 1200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -1.68, distance: 23.5),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 23.5),
      CourseSection(name: 'backstretch', startDistance: 23.5, endDistance: 480.6),
      CourseSection(name: 'corner_3', startDistance: 480.6, endDistance: 661.4),
      CourseSection(name: 'corner_4', startDistance: 661.4, endDistance: 841.3),
      CourseSection(name: 'finish', startDistance: 841.3, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shibaInner1400 = RaceCourseData(
    baseData: NiigataBase.shibaInner,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:39:04
    // Result: niigata shiba_inner 1400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -1.27, distance: 223.5),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 223.5),
      CourseSection(name: 'backstretch', startDistance: 223.5, endDistance: 680.6),
      CourseSection(name: 'corner_3', startDistance: 680.6, endDistance: 861.4),
      CourseSection(name: 'corner_4', startDistance: 861.4, endDistance: 1041.3),
      CourseSection(name: 'finish', startDistance: 1041.3, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData shibaInner2000 = RaceCourseData(
    baseData: NiigataBase.shibaInner,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:39:46
    // Result: niigata shiba_inner 2000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 456.4),
      CourseSection(name: 'corner_1', startDistance: 456.4, endDistance: 640.3),
      CourseSection(name: 'corner_2', startDistance: 640.3, endDistance: 823.5),
      CourseSection(name: 'backstretch', startDistance: 823.5, endDistance: 1280.6),
      CourseSection(name: 'corner_3', startDistance: 1280.6, endDistance: 1461.4),
      CourseSection(name: 'corner_4', startDistance: 1461.4, endDistance: 1641.3),
      CourseSection(name: 'finish', startDistance: 1641.3, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shibaInner2200 = RaceCourseData(
    baseData: NiigataBase.shibaInner,
    raceDistance: 2200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:40:19
    // Result: niigata shiba_inner 2200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 179.33, distance: 218.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 218.3),
      CourseSection(name: 'home_straight', startDistance: 218.3, endDistance: 656.4),
      CourseSection(name: 'corner_1', startDistance: 656.4, endDistance: 840.3),
      CourseSection(name: 'corner_2', startDistance: 840.3, endDistance: 1023.5),
      CourseSection(name: 'backstretch', startDistance: 1023.5, endDistance: 1480.6),
      CourseSection(name: 'corner_3', startDistance: 1480.6, endDistance: 1661.4),
      CourseSection(name: 'corner_4', startDistance: 1661.4, endDistance: 1841.3),
      CourseSection(name: 'finish', startDistance: 1841.3, endDistance: 2200.0),
    ],
  );

  static const RaceCourseData shibaInner2400 = RaceCourseData(
    baseData: NiigataBase.shibaInner,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:40:47
    // Result: niigata shiba_inner 2400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 179.66, distance: 418.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 418.3),
      CourseSection(name: 'home_straight', startDistance: 418.3, endDistance: 856.4),
      CourseSection(name: 'corner_1', startDistance: 856.4, endDistance: 1040.3),
      CourseSection(name: 'corner_2', startDistance: 1040.3, endDistance: 1223.5),
      CourseSection(name: 'backstretch', startDistance: 1223.5, endDistance: 1680.6),
      CourseSection(name: 'corner_3', startDistance: 1680.6, endDistance: 1861.4),
      CourseSection(name: 'corner_4', startDistance: 1861.4, endDistance: 2041.3),
      CourseSection(name: 'finish', startDistance: 2041.3, endDistance: 2400.0),
    ],
  );

  static const RaceCourseData shibaOuter1600 = RaceCourseData(
    baseData: NiigataBase.shibaOuter,
    raceDistance: 1600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:41:31
    // Result: niigata shiba_outer 1600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 595.3),
      CourseSection(name: 'corner_3', startDistance: 595.3, endDistance: 767.0),
      CourseSection(name: 'corner_4', startDistance: 767.0, endDistance: 941.3),
      CourseSection(name: 'finish', startDistance: 941.3, endDistance: 1600.0),
    ],
  );

  static const RaceCourseData shibaOuter1800 = RaceCourseData(
    baseData: NiigataBase.shibaOuter,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:41:57
    // Result: niigata shiba_outer 1800m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -1.02, distance: 31.8),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 31.8),
      CourseSection(name: 'backstretch', startDistance: 31.8, endDistance: 795.3),
      CourseSection(name: 'corner_3', startDistance: 795.3, endDistance: 967.0),
      CourseSection(name: 'corner_4', startDistance: 967.0, endDistance: 1141.3),
      CourseSection(name: 'finish', startDistance: 1141.3, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shibaOuter2000 = RaceCourseData(
    baseData: NiigataBase.shibaOuter,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:42:27
    // Result: niigata shiba_outer 2000m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 0.0, distance: 231.8),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 231.8),
      CourseSection(name: 'backstretch', startDistance: 231.8, endDistance: 995.3),
      CourseSection(name: 'corner_3', startDistance: 995.3, endDistance: 1167.0),
      CourseSection(name: 'corner_4', startDistance: 1167.0, endDistance: 1341.3),
      CourseSection(name: 'finish', startDistance: 1341.3, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData dirt1200 = RaceCourseData(
    baseData: NiigataBase.dirt,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:56:21
    // Result: niigata dirt 1200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 0.0, distance: 101.6),
    ],

    sections: const [
      CourseSection(name: 'start_turf', startDistance: 0.0, endDistance: 68.0),
      CourseSection(name: 'start_dirt', startDistance: 68.0, endDistance: 101.6),
      CourseSection(name: 'backstretch', startDistance: 101.6, endDistance: 556.0),
      CourseSection(name: 'corner_3', startDistance: 556.0, endDistance: 701.8),
      CourseSection(name: 'corner_4', startDistance: 701.8, endDistance: 846.1),
      CourseSection(name: 'finish', startDistance: 846.1, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData dirt1800 = RaceCourseData(
    baseData: NiigataBase.dirt,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:58:38
    // Result: niigata dirt 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 409.9),
      CourseSection(name: 'corner_1', startDistance: 409.9, endDistance: 551.2),
      CourseSection(name: 'corner_2', startDistance: 551.2, endDistance: 701.6),
      CourseSection(name: 'backstretch', startDistance: 701.6, endDistance: 1156.0),
      CourseSection(name: 'corner_3', startDistance: 1156.0, endDistance: 1301.8),
      CourseSection(name: 'corner_4', startDistance: 1301.8, endDistance: 1446.1),
      CourseSection(name: 'finish', startDistance: 1446.1, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData dirt2500 = RaceCourseData(
    baseData: NiigataBase.dirt,
    raceDistance: 2500,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:59:12
    // Result: niigata dirt 2500m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 383.5),
      CourseSection(name: 'corner_3', startDistance: 383.5, endDistance: 529.3),
      CourseSection(name: 'corner_4', startDistance: 529.3, endDistance: 673.6),
      CourseSection(name: 'home_straight', startDistance: 673.6, endDistance: 1109.9),
      CourseSection(name: 'corner_1', startDistance: 1109.9, endDistance: 1251.2),
      CourseSection(name: 'corner_2', startDistance: 1251.2, endDistance: 1401.6),
      CourseSection(name: 'backstretch', startDistance: 1401.6, endDistance: 1856.0),
      CourseSection(name: 'corner_3', startDistance: 1856.0, endDistance: 2001.8),
      CourseSection(name: 'corner_4', startDistance: 2001.8, endDistance: 2146.1),
      CourseSection(name: 'finish', startDistance: 2146.1, endDistance: 2500.0),
    ],
  );

  static const RaceCourseData shibaStraight1000 = RaceCourseData(
    baseData: NiigataBase.shibaStraight,
    raceDistance: 1000,
    // [削除] 誤認されていた approachPath を削除 (v.2.25)
    // [追加] 直線コース専用のセクション定義に修正 (v.2.25)
    sections: const [
      CourseSection(name: 'straight', startDistance: 0.0, endDistance: 1000.0),
    ],
  );

}
