// [追加] 函館競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/hakodate/hakodate_base.dart';

class HakodateCourse {
  static const RaceCourseData shiba1000 = RaceCourseData(
    baseData: HakodateBase.shiba,
    raceDistance: 1000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:14:43
    // Result: hakodate shiba 1000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 291.7),
      CourseSection(name: 'corner_3', startDistance: 291.7, endDistance: 514.6),
      CourseSection(name: 'corner_4', startDistance: 514.6, endDistance: 737.9),
      CourseSection(name: 'finish', startDistance: 737.9, endDistance: 1000.0),
    ],
  );

  static const RaceCourseData shiba1200 = RaceCourseData(
    baseData: HakodateBase.shiba,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:15:12
    // Result: hakodate shiba 1200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 179.46, distance: 119.1),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 119.1),
      CourseSection(name: 'backstretch', startDistance: 119.1, endDistance: 491.7),
      CourseSection(name: 'corner_3', startDistance: 491.7, endDistance: 714.6),
      CourseSection(name: 'corner_4', startDistance: 714.6, endDistance: 937.9),
      CourseSection(name: 'finish', startDistance: 937.9, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shiba1800 = RaceCourseData(
    baseData: HakodateBase.shiba,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:15:40
    // Result: hakodate shiba 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 297.1),
      CourseSection(name: 'corner_1', startDistance: 297.1, endDistance: 508.3),
      CourseSection(name: 'corner_2', startDistance: 508.3, endDistance: 719.1),
      CourseSection(name: 'backstretch', startDistance: 719.1, endDistance: 1091.7),
      CourseSection(name: 'corner_3', startDistance: 1091.7, endDistance: 1314.6),
      CourseSection(name: 'corner_4', startDistance: 1314.6, endDistance: 1537.9),
      CourseSection(name: 'finish', startDistance: 1537.9, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shiba2000 = RaceCourseData(
    baseData: HakodateBase.shiba,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:16:12
    // Result: hakodate shiba 2000m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -1.05, distance: 111.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 111.3),
      CourseSection(name: 'home_straight', startDistance: 111.3, endDistance: 497.1),
      CourseSection(name: 'corner_1', startDistance: 497.1, endDistance: 708.3),
      CourseSection(name: 'corner_2', startDistance: 708.3, endDistance: 919.1),
      CourseSection(name: 'backstretch', startDistance: 919.1, endDistance: 1291.7),
      CourseSection(name: 'corner_3', startDistance: 1291.7, endDistance: 1514.6),
      CourseSection(name: 'corner_4', startDistance: 1514.6, endDistance: 1737.9),
      CourseSection(name: 'finish', startDistance: 1737.9, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shiba2600 = RaceCourseData(
    baseData: HakodateBase.shiba,
    raceDistance: 2600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:16:52
    // Result: hakodate shiba 2600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 265.1),
      CourseSection(name: 'corner_3', startDistance: 265.1, endDistance: 488.0),
      CourseSection(name: 'corner_4', startDistance: 488.0, endDistance: 711.3),
      CourseSection(name: 'home_straight', startDistance: 711.3, endDistance: 1097.1),
      CourseSection(name: 'corner_1', startDistance: 1097.1, endDistance: 1308.3),
      CourseSection(name: 'corner_2', startDistance: 1308.3, endDistance: 1519.1),
      CourseSection(name: 'backstretch', startDistance: 1519.1, endDistance: 1891.7),
      CourseSection(name: 'corner_3', startDistance: 1891.7, endDistance: 2114.6),
      CourseSection(name: 'corner_4', startDistance: 2114.6, endDistance: 2337.9),
      CourseSection(name: 'finish', startDistance: 2337.9, endDistance: 2600.0),
    ],
  );

  static const RaceCourseData dirt1000 = RaceCourseData(
    baseData: HakodateBase.dirt,
    raceDistance: 1000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:18:06
    // Result: hakodate dirt 1000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 373.1),
      CourseSection(name: 'corner_3', startDistance: 373.1, endDistance: 555.5),
      CourseSection(name: 'corner_4', startDistance: 555.5, endDistance: 739.7),
      CourseSection(name: 'finish', startDistance: 739.7, endDistance: 1000.0),
    ],
  );

  static const RaceCourseData dirt1700 = RaceCourseData(
    baseData: HakodateBase.dirt,
    raceDistance: 1700,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:18:41
    // Result: hakodate dirt 1700m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 349.7),
      CourseSection(name: 'corner_1', startDistance: 349.7, endDistance: 523.0),
      CourseSection(name: 'corner_2', startDistance: 523.0, endDistance: 695.7),
      CourseSection(name: 'backstretch', startDistance: 695.7, endDistance: 1073.1),
      CourseSection(name: 'corner_3', startDistance: 1073.1, endDistance: 1255.5),
      CourseSection(name: 'corner_4', startDistance: 1255.5, endDistance: 1439.7),
      CourseSection(name: 'finish', startDistance: 1439.7, endDistance: 1700.0),
    ],
  );

  static const RaceCourseData dirt2400 = RaceCourseData(
    baseData: HakodateBase.dirt,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:19:11
    // Result: hakodate dirt 2400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 297.3),
      CourseSection(name: 'corner_3', startDistance: 297.3, endDistance: 479.7),
      CourseSection(name: 'corner_4', startDistance: 479.7, endDistance: 663.9),
      CourseSection(name: 'home_straight', startDistance: 663.9, endDistance: 1049.7),
      CourseSection(name: 'corner_1', startDistance: 1049.7, endDistance: 1223.0),
      CourseSection(name: 'corner_2', startDistance: 1223.0, endDistance: 1395.7),
      CourseSection(name: 'backstretch', startDistance: 1395.7, endDistance: 1773.1),
      CourseSection(name: 'corner_3', startDistance: 1773.1, endDistance: 1955.5),
      CourseSection(name: 'corner_4', startDistance: 1955.5, endDistance: 2139.7),
      CourseSection(name: 'finish', startDistance: 2139.7, endDistance: 2400.0),
    ],
  );

}
