// [追加] 阪神競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/hanshin/hanshin_base.dart';

class HanshinCourse {
  static const RaceCourseData shibaInner1200 = RaceCourseData(
    baseData: HanshinBase.shibaInner,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:21:30
    // Result: hanshin shiba_inner 1200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 281.4),
      CourseSection(name: 'corner_3', startDistance: 281.4, endDistance: 577.7),
      CourseSection(name: 'corner_4', startDistance: 577.7, endDistance: 843.5),
      CourseSection(name: 'finish', startDistance: 843.5, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shibaInner1400 = RaceCourseData(
    baseData: HanshinBase.shibaInner,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:21:56
    // Result: hanshin shiba_inner 1400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 161.57, distance: 100.4),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 100.4),
      CourseSection(name: 'backstretch', startDistance: 100.4, endDistance: 481.4),
      CourseSection(name: 'corner_3', startDistance: 481.4, endDistance: 777.7),
      CourseSection(name: 'corner_4', startDistance: 777.7, endDistance: 1043.5),
      CourseSection(name: 'finish', startDistance: 1043.5, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData shibaInner2000 = RaceCourseData(
    baseData: HanshinBase.shibaInner,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:22:22
    // Result: hanshin shiba_inner 2000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 348.4),
      CourseSection(name: 'corner_1', startDistance: 348.4, endDistance: 522.8),
      CourseSection(name: 'corner_2', startDistance: 522.8, endDistance: 700.4),
      CourseSection(name: 'backstretch', startDistance: 700.4, endDistance: 1081.4),
      CourseSection(name: 'corner_3', startDistance: 1081.4, endDistance: 1377.7),
      CourseSection(name: 'corner_4', startDistance: 1377.7, endDistance: 1643.5),
      CourseSection(name: 'finish', startDistance: 1643.5, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shibaInner2200 = RaceCourseData(
    baseData: HanshinBase.shibaInner,
    raceDistance: 2200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:22:48
    // Result: hanshin shiba_inner 2200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 0.0, distance: 154.5),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 154.5),
      CourseSection(name: 'home_straight', startDistance: 154.5, endDistance: 548.4),
      CourseSection(name: 'corner_1', startDistance: 548.4, endDistance: 722.8),
      CourseSection(name: 'corner_2', startDistance: 722.8, endDistance: 900.4),
      CourseSection(name: 'backstretch', startDistance: 900.4, endDistance: 1281.4),
      CourseSection(name: 'corner_3', startDistance: 1281.4, endDistance: 1577.7),
      CourseSection(name: 'corner_4', startDistance: 1577.7, endDistance: 1843.5),
      CourseSection(name: 'finish', startDistance: 1843.5, endDistance: 2200.0),
    ],
  );

  static const RaceCourseData shibaInner3000 = RaceCourseData(
    baseData: HanshinBase.shibaInner,
    raceDistance: 3000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:23:28
    // Result: hanshin shiba_inner 3000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 365.7),
      CourseSection(name: 'corner_3', startDistance: 365.7, endDistance: 662.0),
      CourseSection(name: 'corner_4', startDistance: 662.0, endDistance: 927.8),
      CourseSection(name: 'straight', startDistance: 927.8, endDistance: 1340.8),
      CourseSection(name: 'straight', startDistance: 1340.8, endDistance: 1518.4),
      CourseSection(name: 'corner_2', startDistance: 1518.4, endDistance: 1700.4),
      CourseSection(name: 'backstretch', startDistance: 1700.4, endDistance: 2081.4),
      CourseSection(name: 'corner_3', startDistance: 2081.4, endDistance: 2377.7),
      CourseSection(name: 'corner_4', startDistance: 2377.7, endDistance: 2643.5),
      CourseSection(name: 'finish', startDistance: 2643.5, endDistance: 3000.0),
    ],
  );

  static const RaceCourseData shibaOuter1600 = RaceCourseData(
    baseData: HanshinBase.shibaOuter,
    raceDistance: 1600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:24:01
    // Result: hanshin shiba_outer 1600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 490.6),
      CourseSection(name: 'corner_3', startDistance: 490.6, endDistance: 822.5),
      CourseSection(name: 'corner_4', startDistance: 822.5, endDistance: 1126.4),
      CourseSection(name: 'finish', startDistance: 1126.4, endDistance: 1600.0),
    ],
  );

  static const RaceCourseData shibaOuter1800 = RaceCourseData(
    baseData: HanshinBase.shibaOuter,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:24:21
    // Result: hanshin shiba_outer 1800m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 160.97, distance: 113.8),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 113.8),
      CourseSection(name: 'backstretch', startDistance: 113.8, endDistance: 690.6),
      CourseSection(name: 'corner_3', startDistance: 690.6, endDistance: 1022.5),
      CourseSection(name: 'corner_4', startDistance: 1022.5, endDistance: 1326.4),
      CourseSection(name: 'finish', startDistance: 1326.4, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shibaOuter2400 = RaceCourseData(
    baseData: HanshinBase.shibaOuter,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:24:43
    // Result: hanshin shiba_outer 2400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 341.5),
      CourseSection(name: 'corner_1', startDistance: 341.5, endDistance: 524.0),
      CourseSection(name: 'corner_2', startDistance: 524.0, endDistance: 713.8),
      CourseSection(name: 'backstretch', startDistance: 713.8, endDistance: 1290.6),
      CourseSection(name: 'corner_3', startDistance: 1290.6, endDistance: 1622.5),
      CourseSection(name: 'corner_4', startDistance: 1622.5, endDistance: 1926.4),
      CourseSection(name: 'finish', startDistance: 1926.4, endDistance: 2400.0),
    ],
  );

  static const RaceCourseData dirt1200 = RaceCourseData(
    baseData: HanshinBase.dirt,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:25:12
    // Result: hanshin dirt 1200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 373.3),
      CourseSection(name: 'corner_3', startDistance: 373.3, endDistance: 619.9),
      CourseSection(name: 'corner_4', startDistance: 619.9, endDistance: 847.3),
      CourseSection(name: 'finish', startDistance: 847.3, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData dirt1400 = RaceCourseData(
    baseData: HanshinBase.dirt,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:25:39
    // Result: hanshin dirt 1400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 160.91, distance: 194.4),
    ],

    sections: const [
      CourseSection(name: 'start_turf', startDistance: 0.0, endDistance: 126.4),
      CourseSection(name: 'start_dirt', startDistance: 126.4, endDistance: 194.4),
      CourseSection(name: 'backstretch', startDistance: 194.4, endDistance: 573.3),
      CourseSection(name: 'corner_3', startDistance: 573.3, endDistance: 819.9),
      CourseSection(name: 'corner_4', startDistance: 819.9, endDistance: 1047.3),
      CourseSection(name: 'finish', startDistance: 1047.3, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData dirt1800 = RaceCourseData(
    baseData: HanshinBase.dirt,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:26:02
    // Result: hanshin dirt 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 316.6),
      CourseSection(name: 'corner_1', startDistance: 316.6, endDistance: 453.1),
      CourseSection(name: 'corner_2', startDistance: 453.1, endDistance: 594.4),
      CourseSection(name: 'backstretch', startDistance: 594.4, endDistance: 973.3),
      CourseSection(name: 'corner_3', startDistance: 973.3, endDistance: 1219.9),
      CourseSection(name: 'corner_4', startDistance: 1219.9, endDistance: 1447.3),
      CourseSection(name: 'finish', startDistance: 1447.3, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData dirt2000 = RaceCourseData(
    baseData: HanshinBase.dirt,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:26:36
    // Result: hanshin dirt 2000m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -1.74, distance: 129.7),
    ],

    sections: const [
      CourseSection(name: 'start_turf', startDistance: 0.0, endDistance: 58.6),
      CourseSection(name: 'start_dirt', startDistance: 58.6, endDistance: 129.7),
      CourseSection(name: 'home_straight', startDistance: 129.7, endDistance: 516.6),
      CourseSection(name: 'corner_1', startDistance: 516.6, endDistance: 653.1),
      CourseSection(name: 'corner_2', startDistance: 653.1, endDistance: 794.4),
      CourseSection(name: 'backstretch', startDistance: 794.4, endDistance: 1173.3),
      CourseSection(name: 'corner_3', startDistance: 1173.3, endDistance: 1419.9),
      CourseSection(name: 'corner_4', startDistance: 1419.9, endDistance: 1647.3),
      CourseSection(name: 'finish', startDistance: 1647.3, endDistance: 2000.0),
    ],
  );

}
