// [追加] 札幌競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/sapporo/sapporo_base.dart';

class SapporoCourse {
  static const RaceCourseData shiba1000 = RaceCourseData(
    baseData: SapporoBase.shiba,
    raceDistance: 1000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:43:30
    // Result: sapporo shiba 1000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 240.9),
      CourseSection(name: 'corner_3', startDistance: 240.9, endDistance: 487.0),
      CourseSection(name: 'corner_4', startDistance: 487.0, endDistance: 733.9),
      CourseSection(name: 'finish', startDistance: 733.9, endDistance: 1000.0),
    ],
  );

  static const RaceCourseData shiba1200 = RaceCourseData(
    baseData: SapporoBase.shiba,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:44:12
    // Result: sapporo shiba 1200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -179.25, distance: 113.5),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 113.5),
      CourseSection(name: 'backstretch', startDistance: 113.5, endDistance: 440.9),
      CourseSection(name: 'corner_3', startDistance: 440.9, endDistance: 687.0),
      CourseSection(name: 'corner_4', startDistance: 687.0, endDistance: 933.9),
      CourseSection(name: 'finish', startDistance: 933.9, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shiba1500 = RaceCourseData(
    baseData: SapporoBase.shiba,
    raceDistance: 1500,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:45:17
    // Result: sapporo shiba 1500m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 96.9, distance: 171.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 171.3),
      CourseSection(name: 'corner_2', startDistance: 171.3, endDistance: 413.5),
      CourseSection(name: 'backstretch', startDistance: 413.5, endDistance: 740.9),
      CourseSection(name: 'corner_3', startDistance: 740.9, endDistance: 987.0),
      CourseSection(name: 'corner_4', startDistance: 987.0, endDistance: 1233.9),
      CourseSection(name: 'finish', startDistance: 1233.9, endDistance: 1500.0),
    ],
  );

  static const RaceCourseData shiba1800 = RaceCourseData(
    baseData: SapporoBase.shiba,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:46:16
    // Result: sapporo shiba 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 199.6),
      CourseSection(name: 'corner_1', startDistance: 199.6, endDistance: 456.9),
      CourseSection(name: 'corner_2', startDistance: 456.9, endDistance: 713.5),
      CourseSection(name: 'backstretch', startDistance: 713.5, endDistance: 1040.9),
      CourseSection(name: 'corner_3', startDistance: 1040.9, endDistance: 1287.0),
      CourseSection(name: 'corner_4', startDistance: 1287.0, endDistance: 1533.9),
      CourseSection(name: 'finish', startDistance: 1533.9, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shiba2000 = RaceCourseData(
    baseData: SapporoBase.shiba,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:46:49
    // Result: sapporo shiba 2000m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -1.02, distance: 93.0),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 93.0),
      CourseSection(name: 'home_straight', startDistance: 93.0, endDistance: 399.6),
      CourseSection(name: 'corner_1', startDistance: 399.6, endDistance: 656.9),
      CourseSection(name: 'corner_2', startDistance: 656.9, endDistance: 913.5),
      CourseSection(name: 'backstretch', startDistance: 913.5, endDistance: 1240.9),
      CourseSection(name: 'corner_3', startDistance: 1240.9, endDistance: 1487.0),
      CourseSection(name: 'corner_4', startDistance: 1487.0, endDistance: 1733.9),
      CourseSection(name: 'finish', startDistance: 1733.9, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shiba2600 = RaceCourseData(
    baseData: SapporoBase.shiba,
    raceDistance: 2600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:47:30
    // Result: sapporo shiba 2600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 200.0),
      CourseSection(name: 'corner_3', startDistance: 200.0, endDistance: 446.1),
      CourseSection(name: 'corner_4', startDistance: 446.1, endDistance: 693.0),
      CourseSection(name: 'home_straight', startDistance: 693.0, endDistance: 999.6),
      CourseSection(name: 'corner_1', startDistance: 999.6, endDistance: 1256.9),
      CourseSection(name: 'corner_2', startDistance: 1256.9, endDistance: 1513.5),
      CourseSection(name: 'backstretch', startDistance: 1513.5, endDistance: 1840.9),
      CourseSection(name: 'corner_3', startDistance: 1840.9, endDistance: 2087.0),
      CourseSection(name: 'corner_4', startDistance: 2087.0, endDistance: 2333.9),
      CourseSection(name: 'finish', startDistance: 2333.9, endDistance: 2600.0),
    ],
  );

  static const RaceCourseData dirt1000 = RaceCourseData(
    baseData: SapporoBase.dirt,
    raceDistance: 1000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:49:10
    // Result: sapporo dirt 1000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 318.8),
      CourseSection(name: 'corner_3', startDistance: 318.8, endDistance: 527.3),
      CourseSection(name: 'corner_4', startDistance: 527.3, endDistance: 735.7),
      CourseSection(name: 'finish', startDistance: 735.7, endDistance: 1000.0),
    ],
  );

  static const RaceCourseData dirt1700 = RaceCourseData(
    baseData: SapporoBase.dirt,
    raceDistance: 1700,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:49:43
    // Result: sapporo dirt 1700m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 240.4),
      CourseSection(name: 'straight', startDistance: 240.4, endDistance: 464.5),
      CourseSection(name: 'corner_2', startDistance: 464.5, endDistance: 688.6),
      CourseSection(name: 'backstretch', startDistance: 688.6, endDistance: 1018.8),
      CourseSection(name: 'corner_3', startDistance: 1018.8, endDistance: 1227.3),
      CourseSection(name: 'corner_4', startDistance: 1227.3, endDistance: 1435.7),
      CourseSection(name: 'finish', startDistance: 1435.7, endDistance: 1700.0),
    ],
  );

  static const RaceCourseData dirt2400 = RaceCourseData(
    baseData: SapporoBase.dirt,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 23:50:22
    // Result: sapporo dirt 2400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 231.8),
      CourseSection(name: 'corner_3', startDistance: 231.8, endDistance: 440.3),
      CourseSection(name: 'corner_4', startDistance: 440.3, endDistance: 648.7),
      CourseSection(name: 'home_straight', startDistance: 648.7, endDistance: 957.9),
      CourseSection(name: 'corner_1', startDistance: 957.9, endDistance: 1173.3),
      CourseSection(name: 'corner_2', startDistance: 1173.3, endDistance: 1388.6),
      CourseSection(name: 'backstretch', startDistance: 1388.6, endDistance: 1718.8),
      CourseSection(name: 'corner_3', startDistance: 1718.8, endDistance: 1927.3),
      CourseSection(name: 'corner_4', startDistance: 1927.3, endDistance: 2135.7),
      CourseSection(name: 'finish', startDistance: 2135.7, endDistance: 2400.0),
    ],
  );

}
