// [追加] 小倉競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/kokura/kokura_base.dart';

class KokuraCourse {
  static const RaceCourseData shiba1200 = RaceCourseData(
    baseData: KokuraBase.shiba,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:50:41
    // Result: kokura shiba 1200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -179.19, distance: 97.8),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 97.8),
      CourseSection(name: 'backstretch', startDistance: 97.8, endDistance: 513.1),
      CourseSection(name: 'corner_3', startDistance: 513.1, endDistance: 707.6),
      CourseSection(name: 'corner_4', startDistance: 707.6, endDistance: 907.0),
      CourseSection(name: 'finish', startDistance: 907.0, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shiba1700 = RaceCourseData(
    baseData: KokuraBase.shiba,
    raceDistance: 1700,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:51:08
    // Result: kokura shiba 1700m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 197.6),
      CourseSection(name: 'corner_1', startDistance: 197.6, endDistance: 397.5),
      CourseSection(name: 'corner_2', startDistance: 397.5, endDistance: 597.8),
      CourseSection(name: 'backstretch', startDistance: 597.8, endDistance: 1013.1),
      CourseSection(name: 'corner_3', startDistance: 1013.1, endDistance: 1207.6),
      CourseSection(name: 'corner_4', startDistance: 1207.6, endDistance: 1407.0),
      CourseSection(name: 'finish', startDistance: 1407.0, endDistance: 1700.0),
    ],
  );

  static const RaceCourseData shiba1800 = RaceCourseData(
    baseData: KokuraBase.shiba,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:51:31
    // Result: kokura shiba 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 297.6),
      CourseSection(name: 'corner_1', startDistance: 297.6, endDistance: 497.5),
      CourseSection(name: 'corner_2', startDistance: 497.5, endDistance: 697.8),
      CourseSection(name: 'backstretch', startDistance: 697.8, endDistance: 1113.1),
      CourseSection(name: 'corner_3', startDistance: 1113.1, endDistance: 1307.6),
      CourseSection(name: 'corner_4', startDistance: 1307.6, endDistance: 1507.0),
      CourseSection(name: 'finish', startDistance: 1507.0, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shiba2000 = RaceCourseData(
    baseData: KokuraBase.shiba,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:52:02
    // Result: kokura shiba 2000m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -0.91, distance: 91.9),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 91.9),
      CourseSection(name: 'home_straight', startDistance: 91.9, endDistance: 497.6),
      CourseSection(name: 'corner_1', startDistance: 497.6, endDistance: 697.5),
      CourseSection(name: 'corner_2', startDistance: 697.5, endDistance: 897.8),
      CourseSection(name: 'backstretch', startDistance: 897.8, endDistance: 1313.1),
      CourseSection(name: 'corner_3', startDistance: 1313.1, endDistance: 1507.6),
      CourseSection(name: 'corner_4', startDistance: 1507.6, endDistance: 1707.0),
      CourseSection(name: 'finish', startDistance: 1707.0, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shiba2600 = RaceCourseData(
    baseData: KokuraBase.shiba,
    raceDistance: 2600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:52:35
    // Result: kokura shiba 2600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 298.0),
      CourseSection(name: 'corner_3', startDistance: 298.0, endDistance: 492.5),
      CourseSection(name: 'corner_4', startDistance: 492.5, endDistance: 691.9),
      CourseSection(name: 'home_straight', startDistance: 691.9, endDistance: 1097.6),
      CourseSection(name: 'corner_1', startDistance: 1097.6, endDistance: 1297.5),
      CourseSection(name: 'corner_2', startDistance: 1297.5, endDistance: 1497.8),
      CourseSection(name: 'backstretch', startDistance: 1497.8, endDistance: 1913.1),
      CourseSection(name: 'corner_3', startDistance: 1913.1, endDistance: 2107.6),
      CourseSection(name: 'corner_4', startDistance: 2107.6, endDistance: 2307.0),
      CourseSection(name: 'finish', startDistance: 2307.0, endDistance: 2600.0),
    ],
  );

  static const RaceCourseData dirt1000 = RaceCourseData(
    baseData: KokuraBase.dirt,
    raceDistance: 1000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:52:57
    // Result: kokura dirt 1000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 388.6),
      CourseSection(name: 'corner_3', startDistance: 388.6, endDistance: 547.5),
      CourseSection(name: 'corner_4', startDistance: 547.5, endDistance: 708.7),
      CourseSection(name: 'finish', startDistance: 708.7, endDistance: 1000.0),
    ],
  );

  static const RaceCourseData dirt1700 = RaceCourseData(
    baseData: KokuraBase.dirt,
    raceDistance: 1700,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:53:19
    // Result: kokura dirt 1700m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 364.3),
      CourseSection(name: 'corner_1', startDistance: 364.3, endDistance: 525.9),
      CourseSection(name: 'corner_2', startDistance: 525.9, endDistance: 687.1),
      CourseSection(name: 'backstretch', startDistance: 687.1, endDistance: 1088.6),
      CourseSection(name: 'corner_3', startDistance: 1088.6, endDistance: 1247.5),
      CourseSection(name: 'corner_4', startDistance: 1247.5, endDistance: 1408.7),
      CourseSection(name: 'finish', startDistance: 1408.7, endDistance: 1700.0),
    ],
  );

}
