// [追加] 中山競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/nakayama/nakayama_base.dart';

class NakayamaCourse {
  static const RaceCourseData dirt1800 = RaceCourseData(
    baseData: NakayamaBase.dirt,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 22:43:31
    // Result: nakayama dirt 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 392.0),
      CourseSection(name: 'corner_1', startDistance: 392.0, endDistance: 564.5),
      CourseSection(name: 'corner_2', startDistance: 564.5, endDistance: 737.4),
      CourseSection(name: 'backstretch', startDistance: 737.4, endDistance: 1148.0),
      CourseSection(name: 'corner_3', startDistance: 1148.0, endDistance: 1317.6),
      CourseSection(name: 'corner_4', startDistance: 1317.6, endDistance: 1492.0),
      CourseSection(name: 'finish', startDistance: 1492.0, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData dirt2400 = RaceCourseData(
    baseData: NakayamaBase.dirt,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 22:44:32
    // Result: nakayama dirt 2400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 255.0),
      CourseSection(name: 'corner_3', startDistance: 255.0, endDistance: 424.6),
      CourseSection(name: 'corner_4', startDistance: 424.6, endDistance: 599.0),
      CourseSection(name: 'home_straight', startDistance: 599.0, endDistance: 992.0),
      CourseSection(name: 'corner_1', startDistance: 992.0, endDistance: 1164.5),
      CourseSection(name: 'corner_2', startDistance: 1164.5, endDistance: 1337.4),
      CourseSection(name: 'backstretch', startDistance: 1337.4, endDistance: 1748.0),
      CourseSection(name: 'corner_3', startDistance: 1748.0, endDistance: 1917.6),
      CourseSection(name: 'corner_4', startDistance: 1917.6, endDistance: 2092.0),
      CourseSection(name: 'finish', startDistance: 2092.0, endDistance: 2400.0),
    ],
  );

  static const RaceCourseData dirt2500 = RaceCourseData(
    baseData: NakayamaBase.dirt,
    raceDistance: 2500,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-09 22:45:22
    // Result: nakayama dirt 2500m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 355.0),
      CourseSection(name: 'corner_3', startDistance: 355.0, endDistance: 524.6),
      CourseSection(name: 'corner_4', startDistance: 524.6, endDistance: 699.0),
      CourseSection(name: 'home_straight', startDistance: 699.0, endDistance: 1092.0),
      CourseSection(name: 'corner_1', startDistance: 1092.0, endDistance: 1264.5),
      CourseSection(name: 'corner_2', startDistance: 1264.5, endDistance: 1437.4),
      CourseSection(name: 'backstretch', startDistance: 1437.4, endDistance: 1848.0),
      CourseSection(name: 'corner_3', startDistance: 1848.0, endDistance: 2017.6),
      CourseSection(name: 'corner_4', startDistance: 2017.6, endDistance: 2192.0),
      CourseSection(name: 'finish', startDistance: 2192.0, endDistance: 2500.0),
    ],
  );

  static const RaceCourseData shibaInner1800 = RaceCourseData(
    baseData: NakayamaBase.shibaInner,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:04:49
    // Result: nakayama shiba_inner 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 215.6),
      CourseSection(name: 'corner_1', startDistance: 215.6, endDistance: 433.7),
      CourseSection(name: 'corner_2', startDistance: 433.7, endDistance: 652.8),
      CourseSection(name: 'backstretch', startDistance: 652.8, endDistance: 1037.3),
      CourseSection(name: 'corner_3', startDistance: 1037.3, endDistance: 1261.8),
      CourseSection(name: 'corner_4', startDistance: 1261.8, endDistance: 1490.0),
      CourseSection(name: 'finish', startDistance: 1490.0, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shibaInner2000 = RaceCourseData(
    baseData: NakayamaBase.shibaInner,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:05:49
    // Result: nakayama shiba_inner 2000m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -0.71, distance: 22.9),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 22.9),
      CourseSection(name: 'home_straight', startDistance: 22.9, endDistance: 415.6),
      CourseSection(name: 'corner_1', startDistance: 415.6, endDistance: 633.7),
      CourseSection(name: 'corner_2', startDistance: 633.7, endDistance: 852.8),
      CourseSection(name: 'backstretch', startDistance: 852.8, endDistance: 1237.3),
      CourseSection(name: 'corner_3', startDistance: 1237.3, endDistance: 1461.8),
      CourseSection(name: 'corner_4', startDistance: 1461.8, endDistance: 1690.0),
      CourseSection(name: 'finish', startDistance: 1690.0, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shibaInner2500 = RaceCourseData(
    baseData: NakayamaBase.shibaInner,
    raceDistance: 2500,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:07:31
    // Result: nakayama shiba_inner 2500m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -131.99, distance: 102.7),
      CourseApproach(angle: -138.01, distance: 77.1),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 179.8),
      CourseSection(name: 'corner_3', startDistance: 179.8, endDistance: 294.7),
      CourseSection(name: 'corner_4', startDistance: 294.7, endDistance: 522.9),
      CourseSection(name: 'home_straight', startDistance: 522.9, endDistance: 915.6),
      CourseSection(name: 'corner_1', startDistance: 915.6, endDistance: 1133.7),
      CourseSection(name: 'corner_2', startDistance: 1133.7, endDistance: 1352.8),
      CourseSection(name: 'backstretch', startDistance: 1352.8, endDistance: 1737.3),
      CourseSection(name: 'corner_3', startDistance: 1737.3, endDistance: 1961.8),
      CourseSection(name: 'corner_4', startDistance: 1961.8, endDistance: 2190.0),
      CourseSection(name: 'finish', startDistance: 2190.0, endDistance: 2500.0),
    ],
  );

  static const RaceCourseData shibaInner3600 = RaceCourseData(
    baseData: NakayamaBase.shibaInner,
    raceDistance: 3600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:10:50
    // Result: nakayama shiba_inner 3600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 348.5),
      CourseSection(name: 'corner_1', startDistance: 348.5, endDistance: 566.6),
      CourseSection(name: 'corner_2', startDistance: 566.6, endDistance: 785.7),
      CourseSection(name: 'backstretch', startDistance: 785.7, endDistance: 1170.2),
      CourseSection(name: 'corner_3', startDistance: 1170.2, endDistance: 1394.7),
      CourseSection(name: 'corner_4', startDistance: 1394.7, endDistance: 1622.9),
      CourseSection(name: 'home_straight', startDistance: 1622.9, endDistance: 2015.6),
      CourseSection(name: 'corner_1', startDistance: 2015.6, endDistance: 2233.7),
      CourseSection(name: 'corner_2', startDistance: 2233.7, endDistance: 2452.8),
      CourseSection(name: 'backstretch', startDistance: 2452.8, endDistance: 2837.3),
      CourseSection(name: 'corner_3', startDistance: 2837.3, endDistance: 3061.8),
      CourseSection(name: 'corner_4', startDistance: 3061.8, endDistance: 3290.0),
      CourseSection(name: 'finish', startDistance: 3290.0, endDistance: 3600.0),
    ],
  );

  static const RaceCourseData shibaOuter1200 = RaceCourseData(
    baseData: NakayamaBase.shibaOuter,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:17:33
    // Result: nakayama shiba_outer 1200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 328.6),
      CourseSection(name: 'corner_3', startDistance: 328.6, endDistance: 675.5),
      CourseSection(name: 'corner_4', startDistance: 675.5, endDistance: 890.0),
      CourseSection(name: 'finish', startDistance: 890.0, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shibaOuter1600 = RaceCourseData(
    baseData: NakayamaBase.shibaOuter,
    raceDistance: 1600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:18:17
    // Result: nakayama shiba_outer 1600m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 101.07, distance: 195.1),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 195.1),
      CourseSection(name: 'corner_2', startDistance: 195.1, endDistance: 452.8),
      CourseSection(name: 'backstretch', startDistance: 452.8, endDistance: 728.6),
      CourseSection(name: 'corner_3', startDistance: 728.6, endDistance: 1075.5),
      CourseSection(name: 'corner_4', startDistance: 1075.5, endDistance: 1290.0),
      CourseSection(name: 'finish', startDistance: 1290.0, endDistance: 1600.0),
    ],
  );

  static const RaceCourseData shibaOuter2200 = RaceCourseData(
    baseData: NakayamaBase.shibaOuter,
    raceDistance: 2200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:18:57
    // Result: nakayama shiba_outer 2200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -1.91, distance: 50.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 50.3),
      CourseSection(name: 'home_straight', startDistance: 50.3, endDistance: 437.6),
      CourseSection(name: 'corner_1', startDistance: 437.6, endDistance: 664.9),
      CourseSection(name: 'corner_2', startDistance: 664.9, endDistance: 1052.8),
      CourseSection(name: 'backstretch', startDistance: 1052.8, endDistance: 1328.6),
      CourseSection(name: 'corner_3', startDistance: 1328.6, endDistance: 1675.5),
      CourseSection(name: 'corner_4', startDistance: 1675.5, endDistance: 1890.0),
      CourseSection(name: 'finish', startDistance: 1890.0, endDistance: 2200.0),
    ],
  );

  static const RaceCourseData dirt1200 = RaceCourseData(
    baseData: NakayamaBase.dirt,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:19:42
    // Result: nakayama dirt 1200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -179.41, distance: 137.4),
    ],

    sections: const [
      CourseSection(name: 'start_turf', startDistance: 0.0, endDistance: 69.9),
      CourseSection(name: 'start_dirt', startDistance: 69.9, endDistance: 137.4),
      CourseSection(name: 'backstretch', startDistance: 137.4, endDistance: 548.0),
      CourseSection(name: 'corner_3', startDistance: 548.0, endDistance: 717.6),
      CourseSection(name: 'corner_4', startDistance: 717.6, endDistance: 892.0),
      CourseSection(name: 'finish', startDistance: 892.0, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shibaOuter2600 = RaceCourseData(
    baseData: NakayamaBase.shibaOuter,
    raceDistance: 2600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-13 23:23:18
    // Result: nakayama shiba_outer 2600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 235.8),
      CourseSection(name: 'corner_4', startDistance: 235.8, endDistance: 450.3),
      CourseSection(name: 'home_straight', startDistance: 450.3, endDistance: 837.6),
      CourseSection(name: 'corner_1', startDistance: 837.6, endDistance: 1064.9),
      CourseSection(name: 'corner_2', startDistance: 1064.9, endDistance: 1452.8),
      CourseSection(name: 'backstretch', startDistance: 1452.8, endDistance: 1728.6),
      CourseSection(name: 'corner_3', startDistance: 1728.6, endDistance: 2075.5),
      CourseSection(name: 'corner_4', startDistance: 2075.5, endDistance: 2290.0),
      CourseSection(name: 'finish', startDistance: 2290.0, endDistance: 2600.0),
    ],
  );

  static const RaceCourseData dirt1700 = RaceCourseData(
    baseData: NakayamaBase.dirt,
    raceDistance: 1700,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-13 23:23:58
    // Result: nakayama dirt 1700m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 292.0),
      CourseSection(name: 'corner_1', startDistance: 292.0, endDistance: 464.5),
      CourseSection(name: 'corner_2', startDistance: 464.5, endDistance: 637.4),
      CourseSection(name: 'backstretch', startDistance: 637.4, endDistance: 1048.0),
      CourseSection(name: 'corner_3', startDistance: 1048.0, endDistance: 1217.6),
      CourseSection(name: 'corner_4', startDistance: 1217.6, endDistance: 1392.0),
      CourseSection(name: 'finish', startDistance: 1392.0, endDistance: 1700.0),
    ],
  );

}
