// [追加] 京都競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/kyoto/kyoto_base.dart';

class KyotoCourse {
  static const RaceCourseData shibaInner1200 = RaceCourseData(
    baseData: KyotoBase.shibaInner,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:07:18
    // Result: kyoto shiba_inner 1200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 315.1),
      CourseSection(name: 'corner_3', startDistance: 315.1, endDistance: 657.2),
      CourseSection(name: 'corner_4', startDistance: 657.2, endDistance: 871.6),
      CourseSection(name: 'finish', startDistance: 871.6, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shibaInner1400 = RaceCourseData(
    baseData: KyotoBase.shibaInner,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:07:38
    // Result: kyoto shiba_inner 1400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 169.11, distance: 110.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 110.3),
      CourseSection(name: 'backstretch', startDistance: 110.3, endDistance: 515.1),
      CourseSection(name: 'corner_3', startDistance: 515.1, endDistance: 857.2),
      CourseSection(name: 'corner_4', startDistance: 857.2, endDistance: 1071.6),
      CourseSection(name: 'finish', startDistance: 1071.6, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData shibaInner1600 = RaceCourseData(
    baseData: KyotoBase.shibaInner,
    raceDistance: 1600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:08:09
    // Result: kyoto shiba_inner 1600m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 169.43, distance: 310.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 310.3),
      CourseSection(name: 'backstretch', startDistance: 310.3, endDistance: 715.1),
      CourseSection(name: 'corner_3', startDistance: 715.1, endDistance: 1057.2),
      CourseSection(name: 'corner_4', startDistance: 1057.2, endDistance: 1271.6),
      CourseSection(name: 'finish', startDistance: 1271.6, endDistance: 1600.0),
    ],
  );

  static const RaceCourseData shibaInner2000 = RaceCourseData(
    baseData: KyotoBase.shibaInner,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:08:36
    // Result: kyoto shiba_inner 2000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 341.3),
      CourseSection(name: 'corner_1', startDistance: 341.3, endDistance: 513.5),
      CourseSection(name: 'corner_2', startDistance: 513.5, endDistance: 710.3),
      CourseSection(name: 'backstretch', startDistance: 710.3, endDistance: 1115.1),
      CourseSection(name: 'corner_3', startDistance: 1115.1, endDistance: 1457.2),
      CourseSection(name: 'corner_4', startDistance: 1457.2, endDistance: 1671.6),
      CourseSection(name: 'finish', startDistance: 1671.6, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shibaOuter1400 = RaceCourseData(
    baseData: KyotoBase.shibaOuter,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:16:02
    // Result: kyoto shiba_outer 1400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 556.0),
      CourseSection(name: 'corner_3', startDistance: 556.0, endDistance: 819.3),
      CourseSection(name: 'corner_4', startDistance: 819.3, endDistance: 996.3),
      CourseSection(name: 'finish', startDistance: 996.3, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData shibaOuter1600 = RaceCourseData(
    baseData: KyotoBase.shibaOuter,
    raceDistance: 1600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:16:28
    // Result: kyoto shiba_outer 1600m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 169.16, distance: 201.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 201.3),
      CourseSection(name: 'backstretch', startDistance: 201.3, endDistance: 756.0),
      CourseSection(name: 'corner_3', startDistance: 756.0, endDistance: 1019.3),
      CourseSection(name: 'corner_4', startDistance: 1019.3, endDistance: 1196.3),
      CourseSection(name: 'finish', startDistance: 1196.3, endDistance: 1600.0),
    ],
  );

  static const RaceCourseData shibaOuter1800 = RaceCourseData(
    baseData: KyotoBase.shibaOuter,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:16:52
    // Result: kyoto shiba_outer 1800m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 169.2, distance: 401.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 401.3),
      CourseSection(name: 'backstretch', startDistance: 401.3, endDistance: 956.0),
      CourseSection(name: 'corner_3', startDistance: 956.0, endDistance: 1219.3),
      CourseSection(name: 'corner_4', startDistance: 1219.3, endDistance: 1396.3),
      CourseSection(name: 'finish', startDistance: 1396.3, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shibaOuter2200 = RaceCourseData(
    baseData: KyotoBase.shibaOuter,
    raceDistance: 2200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:17:16
    // Result: kyoto shiba_outer 2200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 426.5),
      CourseSection(name: 'corner_1', startDistance: 426.5, endDistance: 617.6),
      CourseSection(name: 'corner_2', startDistance: 617.6, endDistance: 801.3),
      CourseSection(name: 'backstretch', startDistance: 801.3, endDistance: 1356.0),
      CourseSection(name: 'corner_3', startDistance: 1356.0, endDistance: 1619.3),
      CourseSection(name: 'corner_4', startDistance: 1619.3, endDistance: 1796.3),
      CourseSection(name: 'finish', startDistance: 1796.3, endDistance: 2200.0),
    ],
  );

  static const RaceCourseData shibaOuter2400 = RaceCourseData(
    baseData: KyotoBase.shibaOuter,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:17:45
    // Result: kyoto shiba_outer 2400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 1.55, distance: 102.0),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 102.0),
      CourseSection(name: 'home_straight', startDistance: 102.0, endDistance: 626.5),
      CourseSection(name: 'corner_1', startDistance: 626.5, endDistance: 817.6),
      CourseSection(name: 'corner_2', startDistance: 817.6, endDistance: 1001.3),
      CourseSection(name: 'backstretch', startDistance: 1001.3, endDistance: 1556.0),
      CourseSection(name: 'corner_3', startDistance: 1556.0, endDistance: 1819.3),
      CourseSection(name: 'corner_4', startDistance: 1819.3, endDistance: 1996.3),
      CourseSection(name: 'finish', startDistance: 1996.3, endDistance: 2400.0),
    ],
  );

  static const RaceCourseData shibaOuter3000 = RaceCourseData(
    baseData: KyotoBase.shibaOuter,
    raceDistance: 3000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:18:25
    // Result: kyoto shiba_outer 3000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 261.7),
      CourseSection(name: 'corner_3', startDistance: 261.7, endDistance: 525.0),
      CourseSection(name: 'corner_4', startDistance: 525.0, endDistance: 702.0),
      CourseSection(name: 'home_straight', startDistance: 702.0, endDistance: 1226.5),
      CourseSection(name: 'corner_1', startDistance: 1226.5, endDistance: 1417.6),
      CourseSection(name: 'corner_2', startDistance: 1417.6, endDistance: 1601.3),
      CourseSection(name: 'backstretch', startDistance: 1601.3, endDistance: 2156.0),
      CourseSection(name: 'corner_3', startDistance: 2156.0, endDistance: 2419.3),
      CourseSection(name: 'corner_4', startDistance: 2419.3, endDistance: 2596.3),
      CourseSection(name: 'finish', startDistance: 2596.3, endDistance: 3000.0),
    ],
  );

  static const RaceCourseData shibaOuter3200 = RaceCourseData(
    baseData: KyotoBase.shibaOuter,
    raceDistance: 3200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:18:56
    // Result: kyoto shiba_outer 3200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 436.8),
      CourseSection(name: 'straight', startDistance: 436.8, endDistance: 704.0),
      CourseSection(name: 'corner_4', startDistance: 704.0, endDistance: 883.9),
      CourseSection(name: 'home_straight', startDistance: 883.9, endDistance: 1408.4),
      CourseSection(name: 'straight', startDistance: 1408.4, endDistance: 1604.3),
      CourseSection(name: 'corner_2', startDistance: 1604.3, endDistance: 1794.5),
      CourseSection(name: 'backstretch', startDistance: 1794.5, endDistance: 2349.2),
      CourseSection(name: 'straight', startDistance: 2349.2, endDistance: 2614.3),
      CourseSection(name: 'corner_4', startDistance: 2614.3, endDistance: 2796.3),
      CourseSection(name: 'finish', startDistance: 2796.3, endDistance: 3200.0),
    ],
  );

  static const RaceCourseData dirt1200 = RaceCourseData(
    baseData: KyotoBase.dirt,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:19:26
    // Result: kyoto dirt 1200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 427.8),
      CourseSection(name: 'corner_3', startDistance: 427.8, endDistance: 709.9),
      CourseSection(name: 'corner_4', startDistance: 709.9, endDistance: 870.9),
      CourseSection(name: 'finish', startDistance: 870.9, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData dirt1400 = RaceCourseData(
    baseData: KyotoBase.dirt,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:20:05
    // Result: kyoto dirt 1400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 168.23, distance: 204.7),
    ],

    sections: const [
      CourseSection(name: 'start_turf', startDistance: 0.0, endDistance: 137.2),
      CourseSection(name: 'start_dirt', startDistance: 137.2, endDistance: 204.7),
      CourseSection(name: 'backstretch', startDistance: 204.7, endDistance: 627.8),
      CourseSection(name: 'corner_3', startDistance: 627.8, endDistance: 909.9),
      CourseSection(name: 'corner_4', startDistance: 909.9, endDistance: 1070.9),
      CourseSection(name: 'finish', startDistance: 1070.9, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData dirt1800 = RaceCourseData(
    baseData: KyotoBase.dirt,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:20:34
    // Result: kyoto dirt 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 310.4),
      CourseSection(name: 'corner_1', startDistance: 310.4, endDistance: 468.4),
      CourseSection(name: 'corner_2', startDistance: 468.4, endDistance: 604.7),
      CourseSection(name: 'backstretch', startDistance: 604.7, endDistance: 1027.8),
      CourseSection(name: 'corner_3', startDistance: 1027.8, endDistance: 1309.9),
      CourseSection(name: 'corner_4', startDistance: 1309.9, endDistance: 1470.9),
      CourseSection(name: 'finish', startDistance: 1470.9, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData dirt1900 = RaceCourseData(
    baseData: KyotoBase.dirt,
    raceDistance: 1900,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-14 00:21:02
    // Result: kyoto dirt 1900m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 410.4),
      CourseSection(name: 'corner_1', startDistance: 410.4, endDistance: 568.4),
      CourseSection(name: 'corner_2', startDistance: 568.4, endDistance: 704.7),
      CourseSection(name: 'backstretch', startDistance: 704.7, endDistance: 1127.8),
      CourseSection(name: 'corner_3', startDistance: 1127.8, endDistance: 1409.9),
      CourseSection(name: 'corner_4', startDistance: 1409.9, endDistance: 1570.9),
      CourseSection(name: 'finish', startDistance: 1570.9, endDistance: 1900.0),
    ],
  );

}
