// [追加] 中京競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/chukyo/chukyo_base.dart';

class ChukyoCourse {
  static const RaceCourseData shiba1200 = RaceCourseData(
    baseData: ChukyoBase.shiba,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:52:09
    // Result: chukyo shiba 1200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 331.0),
      CourseSection(name: 'corner_3', startDistance: 331.0, endDistance: 590.1),
      CourseSection(name: 'corner_4', startDistance: 590.1, endDistance: 787.5),
      CourseSection(name: 'finish', startDistance: 787.5, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shiba1300 = RaceCourseData(
    baseData: ChukyoBase.shiba,
    raceDistance: 1300,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:53:00
    // Result: chukyo shiba 1300m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 12.1),
      CourseSection(name: 'backstretch', startDistance: 12.1, endDistance: 431.0),
      CourseSection(name: 'corner_3', startDistance: 431.0, endDistance: 690.1),
      CourseSection(name: 'corner_4', startDistance: 690.1, endDistance: 887.5),
      CourseSection(name: 'finish', startDistance: 887.5, endDistance: 1300.0),
    ],
  );

  static const RaceCourseData shiba1400 = RaceCourseData(
    baseData: ChukyoBase.shiba,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:53:39
    // Result: chukyo shiba 1400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 4.7, distance: 112.1),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 112.1),
      CourseSection(name: 'backstretch', startDistance: 112.1, endDistance: 531.0),
      CourseSection(name: 'corner_3', startDistance: 531.0, endDistance: 790.1),
      CourseSection(name: 'corner_4', startDistance: 790.1, endDistance: 987.5),
      CourseSection(name: 'finish', startDistance: 987.5, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData shiba1600 = RaceCourseData(
    baseData: ChukyoBase.shiba,
    raceDistance: 1600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:54:25
    // Result: chukyo shiba 1600m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 51.73, distance: 211.2),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 211.2),
      CourseSection(name: 'corner_2', startDistance: 211.2, endDistance: 312.1),
      CourseSection(name: 'backstretch', startDistance: 312.1, endDistance: 731.0),
      CourseSection(name: 'corner_3', startDistance: 731.0, endDistance: 990.1),
      CourseSection(name: 'corner_4', startDistance: 990.1, endDistance: 1187.5),
      CourseSection(name: 'finish', startDistance: 1187.5, endDistance: 1600.0),
    ],
  );

  static const RaceCourseData shiba2000 = RaceCourseData(
    baseData: ChukyoBase.shiba,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:54:54
    // Result: chukyo shiba 2000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 326.8),
      CourseSection(name: 'corner_1', startDistance: 326.8, endDistance: 518.7),
      CourseSection(name: 'corner_2', startDistance: 518.7, endDistance: 712.1),
      CourseSection(name: 'backstretch', startDistance: 712.1, endDistance: 1131.0),
      CourseSection(name: 'corner_3', startDistance: 1131.0, endDistance: 1390.1),
      CourseSection(name: 'corner_4', startDistance: 1390.1, endDistance: 1587.5),
      CourseSection(name: 'finish', startDistance: 1587.5, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shiba2200 = RaceCourseData(
    baseData: ChukyoBase.shiba,
    raceDistance: 2200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:56:04
    // Result: chukyo shiba 2200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -178.64, distance: 81.6),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 81.6),
      CourseSection(name: 'home_straight', startDistance: 81.6, endDistance: 526.8),
      CourseSection(name: 'corner_1', startDistance: 526.8, endDistance: 718.7),
      CourseSection(name: 'corner_2', startDistance: 718.7, endDistance: 912.1),
      CourseSection(name: 'backstretch', startDistance: 912.1, endDistance: 1331.0),
      CourseSection(name: 'corner_3', startDistance: 1331.0, endDistance: 1590.1),
      CourseSection(name: 'corner_4', startDistance: 1590.1, endDistance: 1787.5),
      CourseSection(name: 'finish', startDistance: 1787.5, endDistance: 2200.0),
    ],
  );

  static const RaceCourseData shiba3000 = RaceCourseData(
    baseData: ChukyoBase.shiba,
    raceDistance: 3000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:57:08
    // Result: chukyo shiba 3000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 6.2),
      CourseSection(name: 'backstretch', startDistance: 6.2, endDistance: 425.1),
      CourseSection(name: 'corner_3', startDistance: 425.1, endDistance: 684.2),
      CourseSection(name: 'corner_4', startDistance: 684.2, endDistance: 881.6),
      CourseSection(name: 'home_straight', startDistance: 881.6, endDistance: 1326.8),
      CourseSection(name: 'corner_1', startDistance: 1326.8, endDistance: 1518.7),
      CourseSection(name: 'corner_2', startDistance: 1518.7, endDistance: 1712.1),
      CourseSection(name: 'backstretch', startDistance: 1712.1, endDistance: 2131.0),
      CourseSection(name: 'corner_3', startDistance: 2131.0, endDistance: 2390.1),
      CourseSection(name: 'corner_4', startDistance: 2390.1, endDistance: 2587.5),
      CourseSection(name: 'finish', startDistance: 2587.5, endDistance: 3000.0),
    ],
  );

  static const RaceCourseData dirt1200 = RaceCourseData(
    baseData: ChukyoBase.dirt,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:57:33
    // Result: chukyo dirt 1200m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 423.2),
      CourseSection(name: 'corner_3', startDistance: 423.2, endDistance: 618.5),
      CourseSection(name: 'corner_4', startDistance: 618.5, endDistance: 789.3),
      CourseSection(name: 'finish', startDistance: 789.3, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData dirt1400 = RaceCourseData(
    baseData: ChukyoBase.dirt,
    raceDistance: 1400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:58:05
    // Result: chukyo dirt 1400m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 4.37, distance: 200.8),
    ],

    sections: const [
      CourseSection(name: 'start_turf', startDistance: 0.0, endDistance: 126.0),
      CourseSection(name: 'start_dirt', startDistance: 126.0, endDistance: 200.8),
      CourseSection(name: 'backstretch', startDistance: 200.8, endDistance: 623.2),
      CourseSection(name: 'corner_3', startDistance: 623.2, endDistance: 818.5),
      CourseSection(name: 'corner_4', startDistance: 818.5, endDistance: 989.3),
      CourseSection(name: 'finish', startDistance: 989.3, endDistance: 1400.0),
    ],
  );

  static const RaceCourseData dirt1800 = RaceCourseData(
    baseData: ChukyoBase.dirt,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:58:30
    // Result: chukyo dirt 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 299.0),
      CourseSection(name: 'corner_1', startDistance: 299.0, endDistance: 445.9),
      CourseSection(name: 'corner_2', startDistance: 445.9, endDistance: 600.8),
      CourseSection(name: 'backstretch', startDistance: 600.8, endDistance: 1023.2),
      CourseSection(name: 'corner_3', startDistance: 1023.2, endDistance: 1218.5),
      CourseSection(name: 'corner_4', startDistance: 1218.5, endDistance: 1389.3),
      CourseSection(name: 'finish', startDistance: 1389.3, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData dirt1900 = RaceCourseData(
    baseData: ChukyoBase.dirt,
    raceDistance: 1900,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 03:58:58
    // Result: chukyo dirt 1900m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 399.0),
      CourseSection(name: 'corner_1', startDistance: 399.0, endDistance: 545.9),
      CourseSection(name: 'corner_2', startDistance: 545.9, endDistance: 700.8),
      CourseSection(name: 'backstretch', startDistance: 700.8, endDistance: 1123.2),
      CourseSection(name: 'corner_3', startDistance: 1123.2, endDistance: 1318.5),
      CourseSection(name: 'corner_4', startDistance: 1318.5, endDistance: 1489.3),
      CourseSection(name: 'finish', startDistance: 1489.3, endDistance: 1900.0),
    ],
  );

}
