// [追加] 福島競馬場 レース距離別データ (v.1.0)
import 'package:hetaumakeiba_v2/models/elevation_model.dart';
import 'package:hetaumakeiba_v2/db/elevations/fukushima/fukushima_base.dart';

class FukushimaCourse {
  static const RaceCourseData shiba1000 = RaceCourseData(
    baseData: FukushimaBase.shiba,
    raceDistance: 1000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:20:05
    // Result: fukushima shiba 1000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 255.2),
      CourseSection(name: 'corner_3', startDistance: 255.2, endDistance: 497.5),
      CourseSection(name: 'corner_4', startDistance: 497.5, endDistance: 708.0),
      CourseSection(name: 'finish', startDistance: 708.0, endDistance: 1000.0),
    ],
  );

  static const RaceCourseData shiba1200 = RaceCourseData(
    baseData: FukushimaBase.shiba,
    raceDistance: 1200,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:20:32
    // Result: fukushima shiba 1200m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 180.0, distance: 117.3),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 117.3),
      CourseSection(name: 'backstretch', startDistance: 117.3, endDistance: 455.2),
      CourseSection(name: 'corner_3', startDistance: 455.2, endDistance: 697.5),
      CourseSection(name: 'corner_4', startDistance: 697.5, endDistance: 908.0),
      CourseSection(name: 'finish', startDistance: 908.0, endDistance: 1200.0),
    ],
  );

  static const RaceCourseData shiba1700 = RaceCourseData(
    baseData: FukushimaBase.shiba,
    raceDistance: 1700,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:21:07
    // Result: fukushima shiba 1700m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 192.1),
      CourseSection(name: 'corner_1', startDistance: 192.1, endDistance: 400.3),
      CourseSection(name: 'corner_2', startDistance: 400.3, endDistance: 617.3),
      CourseSection(name: 'backstretch', startDistance: 617.3, endDistance: 955.2),
      CourseSection(name: 'corner_3', startDistance: 955.2, endDistance: 1197.5),
      CourseSection(name: 'corner_4', startDistance: 1197.5, endDistance: 1408.0),
      CourseSection(name: 'finish', startDistance: 1408.0, endDistance: 1700.0),
    ],
  );

  static const RaceCourseData shiba1800 = RaceCourseData(
    baseData: FukushimaBase.shiba,
    raceDistance: 1800,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:21:37
    // Result: fukushima shiba 1800m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 292.1),
      CourseSection(name: 'corner_1', startDistance: 292.1, endDistance: 500.3),
      CourseSection(name: 'corner_2', startDistance: 500.3, endDistance: 717.3),
      CourseSection(name: 'backstretch', startDistance: 717.3, endDistance: 1055.2),
      CourseSection(name: 'corner_3', startDistance: 1055.2, endDistance: 1297.5),
      CourseSection(name: 'corner_4', startDistance: 1297.5, endDistance: 1508.0),
      CourseSection(name: 'finish', startDistance: 1508.0, endDistance: 1800.0),
    ],
  );

  static const RaceCourseData shiba2000 = RaceCourseData(
    baseData: FukushimaBase.shiba,
    raceDistance: 2000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:22:20
    // Result: fukushima shiba 2000m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: -1.23, distance: 108.0),
    ],

    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 108.0),
      CourseSection(name: 'home_straight', startDistance: 108.0, endDistance: 492.1),
      CourseSection(name: 'corner_1', startDistance: 492.1, endDistance: 700.3),
      CourseSection(name: 'corner_2', startDistance: 700.3, endDistance: 917.3),
      CourseSection(name: 'backstretch', startDistance: 917.3, endDistance: 1255.2),
      CourseSection(name: 'corner_3', startDistance: 1255.2, endDistance: 1497.5),
      CourseSection(name: 'corner_4', startDistance: 1497.5, endDistance: 1708.0),
      CourseSection(name: 'finish', startDistance: 1708.0, endDistance: 2000.0),
    ],
  );

  static const RaceCourseData shiba2600 = RaceCourseData(
    baseData: FukushimaBase.shiba,
    raceDistance: 2600,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:31:44
    // Result: fukushima shiba 2600m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 255.2),
      CourseSection(name: 'corner_3', startDistance: 255.2, endDistance: 497.5),
      CourseSection(name: 'corner_4', startDistance: 497.5, endDistance: 708.0),
      CourseSection(name: 'home_straight', startDistance: 708.0, endDistance: 1092.1),
      CourseSection(name: 'corner_1', startDistance: 1092.1, endDistance: 1300.3),
      CourseSection(name: 'corner_2', startDistance: 1300.3, endDistance: 1517.3),
      CourseSection(name: 'backstretch', startDistance: 1517.3, endDistance: 1855.2),
      CourseSection(name: 'corner_3', startDistance: 1855.2, endDistance: 2097.5),
      CourseSection(name: 'corner_4', startDistance: 2097.5, endDistance: 2308.0),
      CourseSection(name: 'finish', startDistance: 2308.0, endDistance: 2600.0),
    ],
  );

  static const RaceCourseData dirt1000 = RaceCourseData(
    baseData: FukushimaBase.dirt,
    raceDistance: 1000,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:32:16
    // Result: fukushima dirt 1000m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 343.1),
      CourseSection(name: 'corner_3', startDistance: 343.1, endDistance: 541.4),
      CourseSection(name: 'corner_4', startDistance: 541.4, endDistance: 704.3),
      CourseSection(name: 'finish', startDistance: 704.3, endDistance: 1000.0),
    ],
  );

  static const RaceCourseData dirt1150 = RaceCourseData(
    baseData: FukushimaBase.dirt,
    raceDistance: 1150,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:32:50
    // Result: fukushima dirt 1150m

    // ガイドライン等による本線外からの合流ルート
    // 合流点からスタート地点に向かって逆走する相対ベクトルの配列 (angle: 度数法)
    approachPath: const [
      CourseApproach(angle: 180.0, distance: 134.8),
    ],

    sections: const [
      CourseSection(name: 'start_turf', startDistance: 0.0, endDistance: 71.4),
      CourseSection(name: 'start_dirt', startDistance: 71.4, endDistance: 134.8),
      CourseSection(name: 'backstretch', startDistance: 134.8, endDistance: 493.1),
      CourseSection(name: 'corner_3', startDistance: 493.1, endDistance: 691.4),
      CourseSection(name: 'corner_4', startDistance: 691.4, endDistance: 854.3),
      CourseSection(name: 'finish', startDistance: 854.3, endDistance: 1150.0),
    ],
  );

  static const RaceCourseData dirt1700 = RaceCourseData(
    baseData: FukushimaBase.dirt,
    raceDistance: 1700,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:33:22
    // Result: fukushima dirt 1700m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 358.7),
      CourseSection(name: 'corner_1', startDistance: 358.7, endDistance: 515.7),
      CourseSection(name: 'corner_2', startDistance: 515.7, endDistance: 684.8),
      CourseSection(name: 'backstretch', startDistance: 684.8, endDistance: 1043.1),
      CourseSection(name: 'corner_3', startDistance: 1043.1, endDistance: 1241.4),
      CourseSection(name: 'corner_4', startDistance: 1241.4, endDistance: 1404.3),
      CourseSection(name: 'finish', startDistance: 1404.3, endDistance: 1700.0),
    ],
  );

  static const RaceCourseData dirt2400 = RaceCourseData(
    baseData: FukushimaBase.dirt,
    raceDistance: 2400,
    // Generated by Tool Version: v.2.23
    // Generated at: 2026-04-11 01:33:51
    // Result: fukushima dirt 2400m
    sections: const [
      CourseSection(name: 'start', startDistance: 0.0, endDistance: 298.5),
      CourseSection(name: 'corner_3', startDistance: 298.5, endDistance: 496.8),
      CourseSection(name: 'corner_4', startDistance: 496.8, endDistance: 659.7),
      CourseSection(name: 'home_straight', startDistance: 659.7, endDistance: 1058.7),
      CourseSection(name: 'corner_1', startDistance: 1058.7, endDistance: 1215.7),
      CourseSection(name: 'corner_2', startDistance: 1215.7, endDistance: 1384.8),
      CourseSection(name: 'backstretch', startDistance: 1384.8, endDistance: 1743.1),
      CourseSection(name: 'corner_3', startDistance: 1743.1, endDistance: 1941.4),
      CourseSection(name: 'corner_4', startDistance: 1941.4, endDistance: 2104.3),
      CourseSection(name: 'finish', startDistance: 2104.3, endDistance: 2400.0),
    ],
  );

}
